/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uni_leipzig.iwi.gilbreth.VBPODataModel.vbpodatamodel.validation;

import de.uni_leipzig.iwi.gilbreth.VBPODataModel.vbpodatamodel.Asset;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_leipzig.iwi.gilbreth.VBPODataModel.vbpodatamodel.SSF}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SSFValidator {
	boolean validate();

	boolean validateContainedSystems(EList<de.uni_leipzig.iwi.gilbreth.VBPODataModel.vbpodatamodel.System> value);

	boolean validateContainedAssets(EList<Asset> value);

	boolean validateSSFContainsSystem(EList<de.uni_leipzig.iwi.gilbreth.VBPODataModel.vbpodatamodel.System> value);
	boolean validateSSFContainsAsset(EList<Asset> value);
}
