/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.uni_leipzig.iwi.gilbreth.acape.validation;

import de.uni_leipzig.iwi.gilbreth.acape.ConstraintType;
import de.uni_leipzig.iwi.gilbreth.acape.Entity;

/**
 * A sample validator interface for {@link de.uni_leipzig.iwi.gilbreth.acape.Constraint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintValidator {
	boolean validate();

	boolean validateType(ConstraintType value);
	boolean validateLhs(Entity value);
	boolean validateRhs(Entity value);
}
