<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vbpodatamodel"
    nsURI="http://vbpodatamodel/1.0" nsPrefix="vbpodatamodel">
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//IdentifiableEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="productComprisesSystem"
        eType="#//System"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productHasFeature" upperBound="-1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//IdentifiableEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureRealizedByAsset"
        lowerBound="1" upperBound="-1" eType="#//Asset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="#//IdentifiableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reuseCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="setupCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Firm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firmHasSPL" eType="#//SPL"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firmHasSSF" eType="#//SSF"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Competitor" eSuperTypes="#//IdentifiableEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="competitorHasPrice" upperBound="-1"
        eType="#//Price" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomerSegment" eSuperTypes="#//IdentifiableEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentHasWTP" upperBound="-1"
        eType="#//WTP" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Price">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priceForProduct" lowerBound="1"
        eType="#//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sPLContainsProduct" upperBound="-1"
        eType="#//Product" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sPLComprisesofFeature"
        upperBound="-1" eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VBPODataModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasAFirm" eType="#//Firm"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasCompetition" eType="#//Competition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasCustomers" eType="#//Customers"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SSF">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sSFContainsSystem" upperBound="-1"
        eType="#//System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sSFContainsAsset" upperBound="-1"
        eType="#//Asset" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//IdentifiableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemUsesAsset" upperBound="-1"
        eType="#//Asset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdentifiableEntity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Competition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consistsOf" upperBound="-1"
        eType="#//Competitor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customers">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customersConsistsOfCustomerSegments"
        upperBound="-1" eType="#//CustomerSegment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WTP">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wTPForProduct" eType="#//Product"/>
  </eClassifiers>
</ecore:EPackage>
